version: "3"

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - app-network
  backend:
    container_name: backend
    image: flask-backend:latest
    depends_on:
      - jaeger
    # expose:
    #   - '5000'
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
  frontend:
    container_name: frontend
    image: flask-frontend:latest
    depends_on:
      - backend
    environment:
      - COUNTER_ENDPOINT=http://backend:5000
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    ports:
      - "8000:8000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge